/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as BemVindoRouteImport } from './routes/bem-vindo'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as MinhasReservasRouteImport } from './routes/minhas-reservas'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as EspacoSlugRouteImport } from './routes/espaco.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const BemVindoRoute = BemVindoRouteImport.update({
  id: '/bem-vindo',
  path: '/bem-vindo',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasReservasRoute = MinhasReservasRouteImport.update({
  id: '/minhas-reservas',
  path: '/minhas-reservas',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const EspacoSlugRoute = EspacoSlugRouteImport.update({
  id: '/espaco/$slug',
  path: '/espaco/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/bem-vindo': typeof BemVindoRoute
  '/buscar': typeof BuscarRoute
  '/entrar': typeof EntrarRoute
  '/minhas-reservas': typeof MinhasReservasRoute
  '/painel': typeof PainelRoute
  '/espaco/$slug': typeof EspacoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/bem-vindo': typeof BemVindoRoute
  '/buscar': typeof BuscarRoute
  '/entrar': typeof EntrarRoute
  '/minhas-reservas': typeof MinhasReservasRoute
  '/painel': typeof PainelRoute
  '/espaco/$slug': typeof EspacoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/bem-vindo': typeof BemVindoRoute
  '/buscar': typeof BuscarRoute
  '/entrar': typeof EntrarRoute
  '/minhas-reservas': typeof MinhasReservasRoute
  '/painel': typeof PainelRoute
  '/espaco/$slug': typeof EspacoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajuda'
    | '/bem-vindo'
    | '/buscar'
    | '/entrar'
    | '/minhas-reservas'
    | '/painel'
    | '/espaco/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/bem-vindo'
    | '/buscar'
    | '/entrar'
    | '/minhas-reservas'
    | '/painel'
    | '/espaco/$slug'
  id:
    | '__root__'
    | '/'
    | '/ajuda'
    | '/bem-vindo'
    | '/buscar'
    | '/entrar'
    | '/minhas-reservas'
    | '/painel'
    | '/espaco/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjudaRoute: typeof AjudaRoute
  BemVindoRoute: typeof BemVindoRoute
  BuscarRoute: typeof BuscarRoute
  EntrarRoute: typeof EntrarRoute
  MinhasReservasRoute: typeof MinhasReservasRoute
  PainelRoute: typeof PainelRoute
  EspacoSlugRoute: typeof EspacoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bem-vindo': {
      id: '/bem-vindo'
      path: '/bem-vindo'
      fullPath: '/bem-vindo'
      preLoaderRoute: typeof BemVindoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-reservas': {
      id: '/minhas-reservas'
      path: '/minhas-reservas'
      fullPath: '/minhas-reservas'
      preLoaderRoute: typeof MinhasReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espaco/$slug': {
      id: '/espaco/$slug'
      path: '/espaco/$slug'
      fullPath: '/espaco/$slug'
      preLoaderRoute: typeof EspacoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjudaRoute: AjudaRoute,
  BemVindoRoute: BemVindoRoute,
  BuscarRoute: BuscarRoute,
  EntrarRoute: EntrarRoute,
  MinhasReservasRoute: MinhasReservasRoute,
  PainelRoute: PainelRoute,
  EspacoSlugRoute: EspacoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
